- hosts: all
  remote_user: root

  tasks:
  - name: install packages
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
      - dpdk
      - dpdk-tools
      - driverctl
      - tuned-profiles-cpu-partitioning

  - name: modprobe dpdk driver
    modprobe:
      name: "{{ kernel_module }}"

  - name: bind nic to dpdk permanently
    command: "driverctl -v set-override {{ pci_addr }} {{ kernel_module }}"

  - name: stop irqbalance
    service:
      name: irqbalance
      state: stopped
      enabled: no

  - name: add isolated cpus to grub file
    lineinfile:
      path: /etc/default/grub
      regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
      line: "GRUB_CMDLINE_LINUX_DEAFULT=iommu=pt intel_iommu=on isolcpus={{ cpu_list }}"
    register: grub

  - name: update grub
    command: "grub2-mkconfig -o /boot/grub2/grub.cfg"
    when: grub.changed
    register: update_grub

  - name: set pmd-cpu-mask
    openvswitch_db:
      table: open_vswitch
      record: .
      col: other_config
      key: pmd-cpu-mask
      value: "{{ pmd-cpu-mask }}"

  - name: set dpdk-init
    openvswitch_db:
      table: open_vswitch
      record: .
      col: other_config
      key: dpdk-init
      value: true

  - name: set dpdk-socket-mem
    openvswitch_db:
      table: open_vswitch
      record: .
      col: other_config
      key: dpdk-socket-mem
      value: "{{ dpdk-socket-mem }}"

  - name: set dpdk lcore mask
    openvswitch_db:
      table: open_vswitch
      record: .
      col: other_config
      key: dpdk-lcore-mask
      value: "{{ dpdk-lcore-mask}}"

  - name: restart openvswitch service
    service:
      name: openvswitch
      state: restarted
